#
#Mon May 25 10:50:17 CEST 2026
batch.param.file=E\:\\projects\\eclipse-workspace\\Parkinson\\batch\\batch_params.xml
host.0.instances=1
host.0.type=LOCAL
key.directory=C\:\\Users\\fabir/.ssh
model.directory=E\:\\projects\\eclipse-workspace\\Parkinson
output.directory=E\:\\projects\\eclipse-workspace\\Parkinson\\output
param.file=E\:\\projects\\eclipse-workspace\\Parkinson\\Parkinson.rs\\parameters.xml
poll.frequency=1.0
scenario.directory=E\:\\projects\\eclipse-workspace\\Parkinson\\Parkinson.rs
vm.arguments=-XX\:+IgnoreUnrecognizedVMOptions --add-opens\=java.base/java.lang.reflect\=ALL-UNNAMED --add-modules\=ALL-SYSTEM --add-exports\=java.base/jdk.internal.ref\=ALL-UNNAMED --add-exports\=java.base/java.lang\=ALL-UNNAMED --add-exports\=java.xml/com.sun.org.apache.xpath.internal\=ALL-UNNAMED --add-exports\=java.xml/com.sun.org.apache.xpath.internal.objects\=ALL-UNNAMED --add-exports\=java.desktop/sun.awt\=ALL-UNNAMED --add-exports\=java.desktop/sun.java2d\=ALL-UNNAMED --add-opens\=java.base/java.lang\=ALL-UNNAMED --add-opens\=java.base/java.util\=ALL-UNNAMED -Dfile.encoding\=UTF-8 -Dstdout.encoding\=UTF-8 -Dstderr.encoding\=UTF-8 -XX\:+ShowCodeDetailsInExceptionMessages
