#
#Sat May 23 16:24:12 CEST 2026
model.directory=D\:\\Informatica\\UniCAM\\Anno IV\\Multi Agent Systems and DDC\\ParkinsonAgentModel
host.0.type=LOCAL
batch.param.file=D\:\\Informatica\\UniCAM\\Anno IV\\Multi Agent Systems and DDC\\ParkinsonAgentModel\\batch\\batch_params.xml
poll.frequency=1.0
scenario.directory=D\:\\Informatica\\UniCAM\\Anno IV\\Multi Agent Systems and DDC\\ParkinsonAgentModel\\Parkinson.rs
param.file=D\:\\Informatica\\UniCAM\\Anno IV\\Multi Agent Systems and DDC\\ParkinsonAgentModel\\Parkinson.rs\\parameters.xml
key.directory=D\:\\
host.0.instances=2
output.directory=D\:\\Informatica\\UniCAM\\Anno IV\\Multi Agent Systems and DDC\\ParkinsonAgentModel\\output
vm.arguments=-XX\:+IgnoreUnrecognizedVMOptions --add-opens\=java.base/java.lang.reflect\=ALL-UNNAMED --add-modules\=ALL-SYSTEM --add-exports\=java.base/jdk.internal.ref\=ALL-UNNAMED --add-exports\=java.base/java.lang\=ALL-UNNAMED --add-exports\=java.xml/com.sun.org.apache.xpath.internal\=ALL-UNNAMED --add-exports\=java.xml/com.sun.org.apache.xpath.internal.objects\=ALL-UNNAMED --add-exports\=java.desktop/sun.awt\=ALL-UNNAMED --add-exports\=java.desktop/sun.java2d\=ALL-UNNAMED --add-opens\=java.base/java.lang\=ALL-UNNAMED --add-opens\=java.base/java.util\=ALL-UNNAMED -Dfile.encoding\=UTF-8 -Dstdout.encoding\=UTF-8 -Dstderr.encoding\=UTF-8 -XX\:+ShowCodeDetailsInExceptionMessages
