#
#Wed May 27 19:03:59 CEST 2026
model.directory=C\:\\Users\\theca\\Desktop\\unicam\\DCC&MAS\\ParkinsonAgentModel
host.0.type=LOCAL
batch.param.file=C\:\\Users\\theca\\Desktop\\unicam\\DCC&MAS\\ParkinsonAgentModel\\batch\\batch_params.xml
poll.frequency=1.0
scenario.directory=C\:\\Users\\theca\\Desktop\\unicam\\DCC&MAS\\ParkinsonAgentModel\\Parkinson.rs
param.file=C\:\\Users\\theca\\Desktop\\unicam\\DCC&MAS\\ParkinsonAgentModel\\Parkinson.rs\\parameters.xml
key.directory=C\:\\Users\\theca/.ssh
host.0.instances=1
output.directory=C\:\\Users\\theca\\Desktop\\unicam\\DCC&MAS\\ParkinsonAgentModel\\output
vm.arguments=-XX\:+IgnoreUnrecognizedVMOptions --add-opens\=java.base/java.lang.reflect\=ALL-UNNAMED --add-modules\=ALL-SYSTEM --add-exports\=java.base/jdk.internal.ref\=ALL-UNNAMED --add-exports\=java.base/java.lang\=ALL-UNNAMED --add-exports\=java.xml/com.sun.org.apache.xpath.internal\=ALL-UNNAMED --add-exports\=java.xml/com.sun.org.apache.xpath.internal.objects\=ALL-UNNAMED --add-exports\=java.desktop/sun.awt\=ALL-UNNAMED --add-exports\=java.desktop/sun.java2d\=ALL-UNNAMED --add-opens\=java.base/java.lang\=ALL-UNNAMED --add-opens\=java.base/java.util\=ALL-UNNAMED -Dfile.encoding\=UTF-8 -Dstdout.encoding\=UTF-8 -Dstderr.encoding\=UTF-8 -XX\:+ShowCodeDetailsInExceptionMessages
